default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-yaml
      - id: sort-simple-yaml
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix','--no-sort-keys']

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        args: ["--ignore=W503,E501,C901"]
        additional_dependencies: [
          'flake8-print',
          'flake8-debugger',
          ]

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.10'
    hooks:
    - id: bandit

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
